/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import View.View;
import Controller.Controller;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.AppState;

/**
 *
 * @author Profe
 */
public class MainWindow extends JFrame implements View {
    private static MainWindow instance = null;
    
    private String appName;
    private PersonView personView;

    public static MainWindow getInstance () {
      if (instance == null) {
        instance = new MainWindow();
      }
      return instance;
    }
    
    private MainWindow() {
        initComponents();
        appName = "Tutorial GUI 1.0";
        personView = new PersonView();
        jpPersonView.add(personView);
        setTitle (appName);
        repaint();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Controller.getInstance().finish(0);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbExit = new javax.swing.JButton();
        jbGetChecks = new javax.swing.JButton();
        jbSpendChecks = new javax.swing.JButton();
        jsHowManyNewChecks = new javax.swing.JSpinner();
        jbNext = new javax.swing.JButton();
        jpPersonView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbExit.setText("Salir");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jbGetChecks.setText("Obtener Cheques");
        jbGetChecks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetChecksActionPerformed(evt);
            }
        });

        jbSpendChecks.setText("Gastar Cheques");
        jbSpendChecks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSpendChecksActionPerformed(evt);
            }
        });

        jsHowManyNewChecks.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jbNext.setText("Siguiente");
        jbNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextActionPerformed(evt);
            }
        });

        jpPersonView.setPreferredSize(new java.awt.Dimension(555, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPersonView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGetChecks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsHowManyNewChecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbSpendChecks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPersonView, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExit)
                    .addComponent(jbGetChecks)
                    .addComponent(jsHowManyNewChecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSpendChecks)
                    .addComponent(jbNext))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        Controller.getInstance().finish(0);
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbGetChecksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetChecksActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().getNewBankChecks ((Integer) jsHowManyNewChecks.getValue());
        updateView();
    }//GEN-LAST:event_jbGetChecksActionPerformed

    private void jbNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().next();
        updateView();
    }//GEN-LAST:event_jbNextActionPerformed

    private void jbSpendChecksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSpendChecksActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().spendBankChecks (personView.getSelectedChecks());
        updateView();
    }//GEN-LAST:event_jbSpendChecksActionPerformed

    @Override
    public void updateView() {
        jbSpendChecks.setEnabled(Controller.getInstance().getAppState() == AppState.PERSONCANSPEND);
        personView.setPerson(Controller.getInstance().getModelToUI().getCurrent());
    }

    @Override
    public void showView() {
        setVisible(true);
    }
    
    @Override 
    public String getAppName() {
        return appName;
    }

    @Override 
    public ArrayList<String> getNames() {
        NamesCapture namesCapture = new NamesCapture (this);
        return namesCapture.getNames();
    }
    
    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", getAppName(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbGetChecks;
    private javax.swing.JButton jbNext;
    private javax.swing.JButton jbSpendChecks;
    private javax.swing.JPanel jpPersonView;
    private javax.swing.JSpinner jsHowManyNewChecks;
    // End of variables declaration//GEN-END:variables
}
