/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import java.awt.Component;
import java.util.ArrayList;
import model.BankCheckToUI;
import model.PersonToUI;

/**
 *
 * @author Profe
 */
public class PersonView extends javax.swing.JPanel {

    /**
     * Creates new form PersonView
     */
    PersonView() {
        initComponents();
    }
    
    void setPerson (PersonToUI p) {
        jlName.setText(p.getName());
        jlTotal.setText(Integer.toString(p.getTotal()));
        panelChecks.removeAll();
        ArrayList<BankCheckToUI> checks = p.getBankChecks();
        BankCheckView checkView;
        for (BankCheckToUI c : checks) {
            checkView = new BankCheckView();
            checkView.setBankCheck(c);
            panelChecks.add(checkView);
        }
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedChecks () {
        ArrayList<Integer> selectedChecks = new ArrayList<>();
        int i = 0;
        for (Component c : panelChecks.getComponents()) {
            if (((BankCheckView) c).isSelected()) {
                selectedChecks.add(i);
            }
            i++;
        }
        return selectedChecks;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        scrollChecks = new javax.swing.JScrollPane();
        panelChecks = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nombre : ");

        jLabel2.setText("Total ... : ");

        jlName.setText("jLabel3");

        jlTotal.setText("jLabel3");

        panelChecks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mis cheques"));
        scrollChecks.setViewportView(panelChecks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlTotal))
                .addGap(18, 18, 18)
                .addComponent(scrollChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JPanel panelChecks;
    private javax.swing.JScrollPane scrollChecks;
    // End of variables declaration//GEN-END:variables
}
