/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.Parcela;
import modelo.TipoCultivo;
import modelo.Trigo;
import modelo.Soja;
import java.awt.Color;
import java.util.ArrayList;
import modelo.Cultivo;

/**
 *
 * @author Profe
 */
public class VistaParcela extends javax.swing.JPanel {
    //-------------------------------------------------
    // Atributos
    //-------------------------------------------------
    private Parcela parcela;
    private ArrayList<BotonCultivar> botones = new ArrayList<>();
    
    //-------------------------------------------------
    // Constructores
    //-------------------------------------------------
    public VistaParcela(Parcela parcela) {
        this.parcela = parcela;
        initComponents();
        this.setBackground(new Color(255, 255, 255, 0));
        this.pnlParcela.setBackground(new Color(255, 255, 255, 0));

       

        if(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.TRIGO) > 0){
            botones.add(new BotonCultivar(this, TipoCultivo.TRIGO, Trigo.ICONO));
        }
        if(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.SOJA) > 0){
            botones.add(new BotonCultivar(this, TipoCultivo.SOJA, Soja.ICONO));
        }

        for(BotonCultivar b : botones){
            this.botonera.add(b);
        }
    }
    
    //-------------------------------------------------
    // Getters & Setters
    //-------------------------------------------------
    public Parcela getParcela(){
        return this.parcela;
    }
    
    //-------------------------------------------------
    // Funciones
    //-------------------------------------------------
    public void actualizarVista(){
        Cultivo cultivoEnProd = parcela.getPrimerCultivo();
        boolean cultivando = cultivoEnProd != null;
        String titulo = cultivando ? "Cultivando" : "Sin cultivar...";
        String icono = null;
        
        // ----
        // EXAMEN
        // TODO Simplemente, descomentar (si le has llamado igual al metodo getIcono de Producto :)
        icono = cultivando ? cultivoEnProd.getIcono() : "";
        // ----
        // FIN DE EXAMEN
        
        this.lbTitulo.setText(titulo);
        addIconoCultivo(icono);
        actualizarBotonesCultivo();
    }
    
    private void addIconoCultivo(String rutaImagen){
        this.iconoCultivo.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagen)));
    }
    
    private void actualizarBotonesCultivo(){
        for(BotonCultivar b : botones){
            b.setEnabled(this.parcela.puedeProducir()
                    && Controlador.instancia.getCultivosDisponiblesDeUnTipo(b.getTipoCultivo()) > 0);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        pnlParcela = new javax.swing.JPanel();
        iconoCultivo = new javax.swing.JLabel();
        iconoParcela = new javax.swing.JLabel();
        botonera = new javax.swing.JPanel();

        lbTitulo.setText("Cultivando");

        pnlParcela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoCultivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trigo.png"))); // NOI18N
        pnlParcela.add(iconoCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 48));

        iconoParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parcela.png"))); // NOI18N
        pnlParcela.add(iconoParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));

        botonera.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbTitulo))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pnlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonera;
    private javax.swing.JLabel iconoCultivo;
    private javax.swing.JLabel iconoParcela;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnlParcela;
    // End of variables declaration//GEN-END:variables
}
