/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.Parcela;
import modelo.Soja;
import modelo.TipoCultivo;
import modelo.Trigo;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Profe
 */
public class VistaPrincipal extends javax.swing.JFrame implements IVista{
    //-------------------------------------------------
    // Atributos
    //-------------------------------------------------
    private ArrayList<VistaParcela> vistaParcelas = new ArrayList<>();
    
    //-------------------------------------------------
    // Constructores
    //-------------------------------------------------
    public VistaPrincipal() {
        initComponents();
        mapa.setBackground(new Color(255, 255, 255, 0)); 
    }
    
    //-------------------------------------------------
    // Funciones
    //-------------------------------------------------
    public void inicializarVista(){
        for(Parcela parcela : Controlador.instancia.getParcelas()){
            addParcela(parcela);   
        }
    }
    
    public void mostrarVista () {
        this.setVisible(true);
    }

    public void actualizarVista() {
        this.lbNivel.setText(String.valueOf(Controlador.instancia.getNivel()));
        
         
        // ----
        // EXAMEN
        // TODO Completa el método actualizarVista para mostrar el dinero del juego.
        this.lbDinero.setText(String.valueOf(Controlador.instancia.getDinero()));
                
        // TODO Complete el método actualizarVista para mostrar la experiencia del juego en la barra de experiencia.
        this.lbExpBarra.setText(String.valueOf(Controlador.instancia.getExperiencia()));
        this.experiencia.setValue(Controlador.instancia.getExperiencia());
        this.experiencia.setMaximum(Controlador.instancia.getProgresoActual());
        this.lbExpBarra.setText(String.valueOf(Controlador.instancia.getExperiencia()) + "/" +Controlador.instancia.getProgresoActual());
        
        // TODO Complete el método actualizarVista para cambiar el texto del precio de venta del trigo y de la soja
        this.lbDineroVentaTrigo.setText(String.valueOf(Trigo.PRECIO_VENTA));
        this.lbDineroVentaSoja.setText(String.valueOf(Soja.PRECIO_VENTA));
        
         // FIN DE EXAMEN
        // ---- 
        
        this.experiencia.setMaximum(Controlador.instancia.getProgresoActual());
        this.lbExpBarra.setText(String.valueOf(Controlador.instancia.getExperiencia()) + "/" +Controlador.instancia.getProgresoActual());
        this.lbNumTrigo.setText(String.valueOf(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.TRIGO)));
        this.lbNumSoja.setText(String.valueOf(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.SOJA)));
        
        this.lbPrecioParcela.setText(String.valueOf(Parcela.PRECIO));
        this.btnComprarParcela.setEnabled(Controlador.instancia.getDinero() - 15 >= 0);
        

        this.btnVenderSoja.setEnabled(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.TRIGO) > 0);
        this.btnVenderTrigo1.setEnabled(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.SOJA) > 0);

        
         for(VistaParcela pv: vistaParcelas){
            pv.actualizarVista();
        }
        
        repaint();
        revalidate();
    }
    
    private void addParcela(Parcela p){
        VistaParcela pv = new VistaParcela(p);
        vistaParcelas.add(pv);
        mapa.add(pv);
        pv.actualizarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHayDay = new javax.swing.JLabel();
        iconoMoneda = new javax.swing.JLabel();
        lbDinero = new javax.swing.JLabel();
        panelComprarParcela = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPrecioParcela = new javax.swing.JLabel();
        btnComprarParcela = new javax.swing.JButton();
        lbDinero2 = new javax.swing.JLabel();
        pnlVenderTrigo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDineroVentaTrigo = new javax.swing.JLabel();
        btnVenderSoja = new javax.swing.JButton();
        lbDinero3 = new javax.swing.JLabel();
        pnlVenderTr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbDineroVentaSoja = new javax.swing.JLabel();
        btnVenderTrigo1 = new javax.swing.JButton();
        lbDinero4 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        iconoTrigo = new javax.swing.JLabel();
        lbNumTrigo = new javax.swing.JLabel();
        iconoSoja = new javax.swing.JLabel();
        lbNumSoja = new javax.swing.JLabel();
        experiencia = new javax.swing.JProgressBar();
        lbNivel = new javax.swing.JLabel();
        lbExpBarra = new javax.swing.JLabel();
        iconoExp = new javax.swing.JLabel();
        lbExp2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mapa = new javax.swing.JPanel();
        lbHierba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(244, 182, 63));

        lbHayDay.setFont(new java.awt.Font("Phosphate", 0, 30)); // NOI18N
        lbHayDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hayday.jpg"))); // NOI18N

        iconoMoneda.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        iconoMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDinero.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbDinero.setForeground(new java.awt.Color(255, 255, 255));
        lbDinero.setText("0");

        panelComprarParcela.setBackground(new java.awt.Color(244, 182, 63));
        panelComprarParcela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parcela64.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbPrecioParcela.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbPrecioParcela.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioParcela.setText("15");

        btnComprarParcela.setText("Comprar");
        btnComprarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarParcelaActionPerformed(evt);
            }
        });

        lbDinero2.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero2.setText("PARCELA");

        javax.swing.GroupLayout panelComprarParcelaLayout = new javax.swing.GroupLayout(panelComprarParcela);
        panelComprarParcela.setLayout(panelComprarParcelaLayout);
        panelComprarParcelaLayout.setHorizontalGroup(
            panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbPrecioParcela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbDinero2)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(btnComprarParcela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelComprarParcelaLayout.setVerticalGroup(
            panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                .addComponent(lbDinero2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecioParcela, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarParcela)
                .addGap(49, 49, 49))
        );

        pnlVenderTrigo.setBackground(new java.awt.Color(193, 153, 91));
        pnlVenderTrigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trigo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDineroVentaTrigo.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbDineroVentaTrigo.setForeground(new java.awt.Color(255, 255, 255));
        lbDineroVentaTrigo.setText("15");

        btnVenderSoja.setText("Vender");
        btnVenderSoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderSojaActionPerformed(evt);
            }
        });

        lbDinero3.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero3.setText("TRIGO");

        javax.swing.GroupLayout pnlVenderTrigoLayout = new javax.swing.GroupLayout(pnlVenderTrigo);
        pnlVenderTrigo.setLayout(pnlVenderTrigoLayout);
        pnlVenderTrigoLayout.setHorizontalGroup(
            pnlVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVenderSoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVenderTrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVenderTrigoLayout.createSequentialGroup()
                        .addComponent(lbDineroVentaTrigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(lbDinero3))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlVenderTrigoLayout.setVerticalGroup(
            pnlVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderTrigoLayout.createSequentialGroup()
                .addComponent(lbDinero3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDineroVentaTrigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderSoja)
                .addGap(49, 49, 49))
        );

        pnlVenderTr.setBackground(new java.awt.Color(193, 153, 91));
        pnlVenderTr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soja.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDineroVentaSoja.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbDineroVentaSoja.setForeground(new java.awt.Color(255, 255, 255));
        lbDineroVentaSoja.setText("15");

        btnVenderTrigo1.setText("Vender");
        btnVenderTrigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderTrigo1ActionPerformed(evt);
            }
        });

        lbDinero4.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero4.setText("SOJA");

        javax.swing.GroupLayout pnlVenderTrLayout = new javax.swing.GroupLayout(pnlVenderTr);
        pnlVenderTr.setLayout(pnlVenderTrLayout);
        pnlVenderTrLayout.setHorizontalGroup(
            pnlVenderTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVenderTrigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVenderTrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVenderTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDinero4)
                    .addGroup(pnlVenderTrLayout.createSequentialGroup()
                        .addComponent(lbDineroVentaSoja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlVenderTrLayout.setVerticalGroup(
            pnlVenderTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderTrLayout.createSequentialGroup()
                .addComponent(lbDinero4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVenderTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDineroVentaSoja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderTrigo1)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbHayDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComprarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlVenderTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlVenderTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(lbDinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoMoneda)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbHayDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelComprarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlVenderTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iconoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(pnlVenderTr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProductos.setBackground(new java.awt.Color(255, 153, 102));

        iconoTrigo.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoTrigo.setForeground(new java.awt.Color(255, 255, 255));
        iconoTrigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trigo.png"))); // NOI18N

        lbNumTrigo.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumTrigo.setForeground(new java.awt.Color(255, 255, 255));
        lbNumTrigo.setText("0");

        iconoSoja.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoSoja.setForeground(new java.awt.Color(255, 255, 255));
        iconoSoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soja.png"))); // NOI18N

        lbNumSoja.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumSoja.setForeground(new java.awt.Color(255, 255, 255));
        lbNumSoja.setText("0");

        experiencia.setBackground(new java.awt.Color(37, 162, 180));
        experiencia.setForeground(new java.awt.Color(106, 171, 255));
        experiencia.setValue(57);

        lbNivel.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(255, 255, 255));
        lbNivel.setText("1");

        lbExpBarra.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbExpBarra.setForeground(new java.awt.Color(255, 255, 255));
        lbExpBarra.setText("0/3");

        iconoExp.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoExp.setForeground(new java.awt.Color(255, 255, 255));
        iconoExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exp.png"))); // NOI18N

        lbExp2.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbExp2.setForeground(new java.awt.Color(255, 255, 255));
        lbExp2.setText("Nivel");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoTrigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumTrigo)
                .addGap(39, 39, 39)
                .addComponent(iconoSoja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumSoja)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbExp2)
                        .addGap(65, 65, 65)
                        .addComponent(lbNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconoExp))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(lbExpBarra)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumSoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbExp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(iconoSoja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbNumTrigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconoTrigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbExpBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconoExp)
                                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mapa.setLayout(new java.awt.GridLayout(2, 4));

        lbHierba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbHierba)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbHierba, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lbHierba.getAccessibleContext().setAccessibleName("lbHierba");
        lbHierba.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 658, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(597, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarParcelaActionPerformed
        Parcela parcela = new Parcela();
        Controlador.instancia.comprar(parcela);
        addParcela(parcela);
    }//GEN-LAST:event_btnComprarParcelaActionPerformed

    private void btnVenderSojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderSojaActionPerformed
        Controlador.instancia.vender(TipoCultivo.TRIGO);
    }//GEN-LAST:event_btnVenderSojaActionPerformed

    private void btnVenderTrigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderTrigo1ActionPerformed
        Controlador.instancia.vender(TipoCultivo.SOJA);
    }//GEN-LAST:event_btnVenderTrigo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarParcela;
    private javax.swing.JButton btnVenderSoja;
    private javax.swing.JButton btnVenderTrigo1;
    private javax.swing.JProgressBar experiencia;
    private javax.swing.JLabel iconoExp;
    private javax.swing.JLabel iconoMoneda;
    private javax.swing.JLabel iconoSoja;
    private javax.swing.JLabel iconoTrigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbDinero;
    private javax.swing.JLabel lbDinero2;
    private javax.swing.JLabel lbDinero3;
    private javax.swing.JLabel lbDinero4;
    private javax.swing.JLabel lbDineroVentaSoja;
    private javax.swing.JLabel lbDineroVentaTrigo;
    private javax.swing.JLabel lbExp2;
    private javax.swing.JLabel lbExpBarra;
    private javax.swing.JLabel lbHayDay;
    private javax.swing.JLabel lbHierba;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNumSoja;
    private javax.swing.JLabel lbNumTrigo;
    private javax.swing.JLabel lbPrecioParcela;
    private javax.swing.JPanel mapa;
    private javax.swing.JPanel panelComprarParcela;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel pnlVenderTr;
    private javax.swing.JPanel pnlVenderTrigo;
    // End of variables declaration//GEN-END:variables
}
