/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.Animal;
import modelo.TipoProductoAnimal;
import java.awt.Color;
import modelo.Gallina;
import modelo.Huevo;
import modelo.Leche;
import modelo.ProductoAnimal;
import modelo.Vaca;

/**
 *
 * @author Profe
 */
public class VistaAnimal extends javax.swing.JPanel {
    //-------------------------------------------------
    // Atributos
    //-------------------------------------------------
    private Animal animal;
    private BotonProducir boton;
    
    //-------------------------------------------------
    // Constructores
    //-------------------------------------------------
    public VistaAnimal(Animal animal) {
        this.animal = animal;
        initComponents();
        this.setBackground(new Color(255, 255, 255, 0));
        this.pnlParcela.setBackground(new Color(255, 255, 255, 0));
        
        
       

        if(this.animal instanceof Gallina){
            this.iconoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource(Gallina.ICONO)));
            boton = new BotonProducir(this, TipoProductoAnimal.HUEVO, Huevo.ICONO);
        }
        else if(this.animal instanceof Vaca){
            this.iconoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource(Vaca.ICONO)));
            boton = new BotonProducir(this, TipoProductoAnimal.LECHE, Leche.ICONO);
        }
        
        if(this.boton != null){
            botonera.add(boton);
        }
        
    }
    
    //-------------------------------------------------
    // Getters & Setters
    //-------------------------------------------------
    public Animal getAnimal(){
        return this.animal;
    }
    
    //-------------------------------------------------
    // Funciones
    //-------------------------------------------------
    public void actualizarVista(){
        boolean produciendo = this.animal.estaProduciendo();
        String titulo = produciendo ? "Produciendo" : "Descansando Zzz";
        String icono = produciendo ? this.animal.getProduccion().get(0).getIcono() : "";
        this.lbTitulo.setText(titulo);
        addIconoProducto(icono);
        actualizarBotonesProducto();
    }
    
    private void addIconoProducto(String rutaImagen){
        this.iconoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagen)));
    }
    
    private void actualizarBotonesProducto(){
        boolean piensoSuficiente = false;
        if(this.animal instanceof Gallina){
            piensoSuficiente = Controlador.instancia.getPiensoGallinaDisponible() - Gallina.PIENSO >= 0;
        }
        else if(this.animal instanceof Vaca){
            piensoSuficiente = Controlador.instancia.getPiensoVacaDisponible() - Vaca.PIENSO >= 0;
        }
        this.boton.setEnabled(this.animal.puedeProducir() && piensoSuficiente);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        pnlParcela = new javax.swing.JPanel();
        iconoProducto = new javax.swing.JLabel();
        iconoAnimal = new javax.swing.JLabel();
        botonera = new javax.swing.JPanel();

        lbTitulo.setText("Produciendo...");

        pnlParcela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huevo40.png"))); // NOI18N
        pnlParcela.add(iconoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 40, 48));

        iconoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gallina.png"))); // NOI18N
        pnlParcela.add(iconoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 140));

        botonera.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonera;
    private javax.swing.JLabel iconoAnimal;
    private javax.swing.JLabel iconoProducto;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnlParcela;
    // End of variables declaration//GEN-END:variables
}
