/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.Animal;
import modelo.Leche;
import modelo.TipoProductoAnimal;
import modelo.Huevo;
import java.awt.Color;
import java.util.ArrayList;
import modelo.Gallina;
import modelo.Vaca;

/**
 *
 * @author Profe
 */
public class VistaPrincipal extends javax.swing.JFrame implements IVista{
    //-------------------------------------------------
    // Atributos
    //-------------------------------------------------
    private ArrayList<VistaAnimal> vistaParcelas = new ArrayList<>();
    
    //-------------------------------------------------
    // Constructores
    //-------------------------------------------------
    public VistaPrincipal() {
        initComponents();
        mapa.setBackground(new Color(255, 255, 255, 0)); 
    }
    
    //-------------------------------------------------
    // Funciones
    //-------------------------------------------------
    public void inicializarVista(){
        for(Animal parcela : Controlador.instancia.getAnimales()){
            addAnimal(parcela);   
        }
    }
    
    public void mostrarVista () {
        this.setVisible(true);
    }

    public void actualizarVista() {
        this.lbNivel.setText(String.valueOf(Controlador.instancia.getNivel()));
        this.lbDinero.setText(String.valueOf(Controlador.instancia.getDinero()));
        this.lbExpBarra.setText(String.valueOf(Controlador.instancia.getExperiencia()));
        this.experiencia.setValue(Controlador.instancia.getExperiencia());
        this.experiencia.setMaximum(Controlador.instancia.getProgresoActual());
        this.lbExpBarra.setText(String.valueOf(Controlador.instancia.getExperiencia()) + "/" +Controlador.instancia.getProgresoActual());
        
        this.lbNumPiensoGallina.setText(String.valueOf(Controlador.instancia.getPiensoGallinaDisponible()));
        this.lbNumPiensoVaca.setText(String.valueOf(Controlador.instancia.getPiensoVacaDisponible()));
        
        this.lbPrecioGallina.setText(String.valueOf(Gallina.PRECIO));
        this.btnComprarGallina.setEnabled(Controlador.instancia.getDinero() - Gallina.PRECIO >= 0);
        
        this.lbPrecioVaca.setText(String.valueOf(Vaca.PRECIO));
        this.btnComprarVaca.setEnabled(Controlador.instancia.getDinero() - Vaca.PRECIO >= 0);
        
        
        this.lbDineroVentaHuevo.setText(String.valueOf(Huevo.PRECIO_VENTA));
        this.btnVenderHuevo.setEnabled(Controlador.instancia.getProductosDisponiblesDeUnTipo(TipoProductoAnimal.HUEVO) > 0);
        this.lbNumHuevos.setText(String.valueOf(Controlador.instancia.getProductosDisponiblesDeUnTipo(TipoProductoAnimal.HUEVO)));
        
        this.lbDineroVentaLeche.setText(String.valueOf(Leche.PRECIO_VENTA));
        this.lbNumLeches.setText(String.valueOf(Controlador.instancia.getProductosDisponiblesDeUnTipo(TipoProductoAnimal.LECHE)));
        this.btnVenderLeche.setEnabled(Controlador.instancia.getProductosDisponiblesDeUnTipo(TipoProductoAnimal.LECHE) > 0);

        for(VistaAnimal pv: vistaParcelas){
            pv.actualizarVista();
        }
        
        repaint();
        revalidate();
    }
    
    private void addAnimal(Animal a){
        VistaAnimal v = new VistaAnimal(a);
        vistaParcelas.add(v);
        mapa.add(v);
        v.actualizarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHayDay = new javax.swing.JLabel();
        iconoMoneda = new javax.swing.JLabel();
        lbDinero = new javax.swing.JLabel();
        panelComprarVaca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPrecioGallina = new javax.swing.JLabel();
        btnComprarGallina = new javax.swing.JButton();
        lbDinero2 = new javax.swing.JLabel();
        pnlVenderHuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDineroVentaHuevo = new javax.swing.JLabel();
        btnVenderHuevo = new javax.swing.JButton();
        lbDinero3 = new javax.swing.JLabel();
        pnlVenderLeche = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbDineroVentaLeche = new javax.swing.JLabel();
        btnVenderLeche = new javax.swing.JButton();
        lbDinero4 = new javax.swing.JLabel();
        panelComprarVaca1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbPrecioVaca = new javax.swing.JLabel();
        btnComprarVaca = new javax.swing.JButton();
        lbDinero5 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        iconoPiensoGallina = new javax.swing.JLabel();
        lbNumPiensoGallina = new javax.swing.JLabel();
        iconoPiensoVaca = new javax.swing.JLabel();
        lbNumPiensoVaca = new javax.swing.JLabel();
        experiencia = new javax.swing.JProgressBar();
        lbNivel = new javax.swing.JLabel();
        lbExpBarra = new javax.swing.JLabel();
        iconoExp = new javax.swing.JLabel();
        lbExp2 = new javax.swing.JLabel();
        iconoHuevos = new javax.swing.JLabel();
        lbNumHuevos = new javax.swing.JLabel();
        iconoLeche = new javax.swing.JLabel();
        lbNumLeches = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mapa = new javax.swing.JPanel();
        lbHierba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(244, 182, 63));

        lbHayDay.setFont(new java.awt.Font("Phosphate", 0, 30)); // NOI18N
        lbHayDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hayday.jpg"))); // NOI18N

        iconoMoneda.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        iconoMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDinero.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbDinero.setForeground(new java.awt.Color(255, 255, 255));
        lbDinero.setText("0");

        panelComprarVaca.setBackground(new java.awt.Color(244, 182, 63));
        panelComprarVaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gallina32.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbPrecioGallina.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbPrecioGallina.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioGallina.setText("15");

        btnComprarGallina.setText("Comprar");
        btnComprarGallina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarGallinaActionPerformed(evt);
            }
        });

        lbDinero2.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero2.setText("GALLINA");

        javax.swing.GroupLayout panelComprarVacaLayout = new javax.swing.GroupLayout(panelComprarVaca);
        panelComprarVaca.setLayout(panelComprarVacaLayout);
        panelComprarVacaLayout.setHorizontalGroup(
            panelComprarVacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarVacaLayout.createSequentialGroup()
                .addGroup(panelComprarVacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarVacaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbPrecioGallina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panelComprarVacaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbDinero2)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(btnComprarGallina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelComprarVacaLayout.setVerticalGroup(
            panelComprarVacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarVacaLayout.createSequentialGroup()
                .addComponent(lbDinero2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelComprarVacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecioGallina, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarGallina)
                .addGap(49, 49, 49))
        );

        pnlVenderHuevo.setBackground(new java.awt.Color(193, 153, 91));
        pnlVenderHuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huevo40.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDineroVentaHuevo.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbDineroVentaHuevo.setForeground(new java.awt.Color(255, 255, 255));
        lbDineroVentaHuevo.setText("15");

        btnVenderHuevo.setText("Vender");
        btnVenderHuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderHuevoActionPerformed(evt);
            }
        });

        lbDinero3.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero3.setText("HUEVO");

        javax.swing.GroupLayout pnlVenderHuevoLayout = new javax.swing.GroupLayout(pnlVenderHuevo);
        pnlVenderHuevo.setLayout(pnlVenderHuevoLayout);
        pnlVenderHuevoLayout.setHorizontalGroup(
            pnlVenderHuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVenderHuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVenderHuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVenderHuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVenderHuevoLayout.createSequentialGroup()
                        .addComponent(lbDineroVentaHuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(lbDinero3))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlVenderHuevoLayout.setVerticalGroup(
            pnlVenderHuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderHuevoLayout.createSequentialGroup()
                .addComponent(lbDinero3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVenderHuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDineroVentaHuevo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderHuevo)
                .addGap(49, 49, 49))
        );

        pnlVenderLeche.setBackground(new java.awt.Color(193, 153, 91));
        pnlVenderLeche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leche40.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbDineroVentaLeche.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbDineroVentaLeche.setForeground(new java.awt.Color(255, 255, 255));
        lbDineroVentaLeche.setText("15");

        btnVenderLeche.setText("Vender");
        btnVenderLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderLecheActionPerformed(evt);
            }
        });

        lbDinero4.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero4.setText("LECHE");

        javax.swing.GroupLayout pnlVenderLecheLayout = new javax.swing.GroupLayout(pnlVenderLeche);
        pnlVenderLeche.setLayout(pnlVenderLecheLayout);
        pnlVenderLecheLayout.setHorizontalGroup(
            pnlVenderLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVenderLeche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVenderLecheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVenderLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDinero4)
                    .addGroup(pnlVenderLecheLayout.createSequentialGroup()
                        .addComponent(lbDineroVentaLeche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlVenderLecheLayout.setVerticalGroup(
            pnlVenderLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderLecheLayout.createSequentialGroup()
                .addComponent(lbDinero4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVenderLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDineroVentaLeche, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderLeche)
                .addGap(49, 49, 49))
        );

        panelComprarVaca1.setBackground(new java.awt.Color(244, 182, 63));
        panelComprarVaca1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vaca32.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbPrecioVaca.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbPrecioVaca.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioVaca.setText("15");

        btnComprarVaca.setText("Comprar");
        btnComprarVaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarVacaActionPerformed(evt);
            }
        });

        lbDinero5.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        lbDinero5.setText("VACA");

        javax.swing.GroupLayout panelComprarVaca1Layout = new javax.swing.GroupLayout(panelComprarVaca1);
        panelComprarVaca1.setLayout(panelComprarVaca1Layout);
        panelComprarVaca1Layout.setHorizontalGroup(
            panelComprarVaca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarVaca1Layout.createSequentialGroup()
                .addGroup(panelComprarVaca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarVaca1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbPrecioVaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(panelComprarVaca1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbDinero5)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(btnComprarVaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelComprarVaca1Layout.setVerticalGroup(
            panelComprarVaca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarVaca1Layout.createSequentialGroup()
                .addComponent(lbDinero5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelComprarVaca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecioVaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarVaca)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbHayDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComprarVaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelComprarVaca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlVenderHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlVenderLeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(lbDinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoMoneda)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbHayDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelComprarVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlVenderHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iconoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlVenderLeche, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelComprarVaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProductos.setBackground(new java.awt.Color(255, 153, 102));

        iconoPiensoGallina.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoPiensoGallina.setForeground(new java.awt.Color(255, 255, 255));
        iconoPiensoGallina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pienso_gallina32.png"))); // NOI18N

        lbNumPiensoGallina.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumPiensoGallina.setForeground(new java.awt.Color(255, 255, 255));
        lbNumPiensoGallina.setText("0");

        iconoPiensoVaca.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoPiensoVaca.setForeground(new java.awt.Color(255, 255, 255));
        iconoPiensoVaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pienso_vaca32.png"))); // NOI18N

        lbNumPiensoVaca.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumPiensoVaca.setForeground(new java.awt.Color(255, 255, 255));
        lbNumPiensoVaca.setText("0");

        experiencia.setBackground(new java.awt.Color(37, 162, 180));
        experiencia.setForeground(new java.awt.Color(106, 171, 255));
        experiencia.setValue(57);

        lbNivel.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(255, 255, 255));
        lbNivel.setText("1");

        lbExpBarra.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lbExpBarra.setForeground(new java.awt.Color(255, 255, 255));
        lbExpBarra.setText("0/3");

        iconoExp.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoExp.setForeground(new java.awt.Color(255, 255, 255));
        iconoExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exp.png"))); // NOI18N

        lbExp2.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbExp2.setForeground(new java.awt.Color(255, 255, 255));
        lbExp2.setText("Nivel");

        iconoHuevos.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoHuevos.setForeground(new java.awt.Color(255, 255, 255));
        iconoHuevos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huevo40.png"))); // NOI18N

        lbNumHuevos.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumHuevos.setForeground(new java.awt.Color(255, 255, 255));
        lbNumHuevos.setText("0");

        iconoLeche.setFont(new java.awt.Font("Phosphate", 0, 13)); // NOI18N
        iconoLeche.setForeground(new java.awt.Color(255, 255, 255));
        iconoLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leche40.png"))); // NOI18N

        lbNumLeches.setFont(new java.awt.Font("Phosphate", 0, 25)); // NOI18N
        lbNumLeches.setForeground(new java.awt.Color(255, 255, 255));
        lbNumLeches.setText("0");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoPiensoGallina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumPiensoGallina)
                .addGap(39, 39, 39)
                .addComponent(iconoPiensoVaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumPiensoVaca)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbExp2)
                        .addGap(65, 65, 65)
                        .addComponent(lbNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconoExp))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(lbExpBarra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(lbNumLeches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoLeche)
                .addGap(43, 43, 43)
                .addComponent(lbNumHuevos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoHuevos)
                .addContainerGap())
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumPiensoVaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbExp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(iconoPiensoVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbNumPiensoGallina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconoPiensoGallina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbExpBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconoExp)
                                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbNumLeches, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconoLeche, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbNumHuevos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconoHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mapa.setLayout(new java.awt.GridLayout(2, 4));

        lbHierba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbHierba)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbHierba, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lbHierba.getAccessibleContext().setAccessibleName("lbHierba");
        lbHierba.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 658, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(605, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarGallinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarGallinaActionPerformed
        Gallina gallina = new Gallina();
        addAnimal(gallina);
        Controlador.instancia.comprar(gallina);
    }//GEN-LAST:event_btnComprarGallinaActionPerformed

    private void btnVenderHuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderHuevoActionPerformed
        Controlador.instancia.vender(TipoProductoAnimal.HUEVO);
    }//GEN-LAST:event_btnVenderHuevoActionPerformed

    private void btnVenderLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderLecheActionPerformed
        Controlador.instancia.vender(TipoProductoAnimal.LECHE);
    }//GEN-LAST:event_btnVenderLecheActionPerformed

    private void btnComprarVacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarVacaActionPerformed
        Vaca vaca = new Vaca();
        addAnimal(vaca);
        Controlador.instancia.comprar(vaca);
    }//GEN-LAST:event_btnComprarVacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarGallina;
    private javax.swing.JButton btnComprarVaca;
    private javax.swing.JButton btnVenderHuevo;
    private javax.swing.JButton btnVenderLeche;
    private javax.swing.JProgressBar experiencia;
    private javax.swing.JLabel iconoExp;
    private javax.swing.JLabel iconoHuevos;
    private javax.swing.JLabel iconoLeche;
    private javax.swing.JLabel iconoMoneda;
    private javax.swing.JLabel iconoPiensoGallina;
    private javax.swing.JLabel iconoPiensoVaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbDinero;
    private javax.swing.JLabel lbDinero2;
    private javax.swing.JLabel lbDinero3;
    private javax.swing.JLabel lbDinero4;
    private javax.swing.JLabel lbDinero5;
    private javax.swing.JLabel lbDineroVentaHuevo;
    private javax.swing.JLabel lbDineroVentaLeche;
    private javax.swing.JLabel lbExp2;
    private javax.swing.JLabel lbExpBarra;
    private javax.swing.JLabel lbHayDay;
    private javax.swing.JLabel lbHierba;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNumHuevos;
    private javax.swing.JLabel lbNumLeches;
    private javax.swing.JLabel lbNumPiensoGallina;
    private javax.swing.JLabel lbNumPiensoVaca;
    private javax.swing.JLabel lbPrecioGallina;
    private javax.swing.JLabel lbPrecioVaca;
    private javax.swing.JPanel mapa;
    private javax.swing.JPanel panelComprarVaca;
    private javax.swing.JPanel panelComprarVaca1;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel pnlVenderHuevo;
    private javax.swing.JPanel pnlVenderLeche;
    // End of variables declaration//GEN-END:variables
}
