HOME = .
BIN = $(HOME)/.
SRC = $(HOME)/.
OBJ = $(HOME)/.
LIB = $(HOME)/.
INCLUDE = $(HOME)/.

all: $(BIN)/uso_hash_abierto

$(BIN)/uso_hash_abierto : $(OBJ)/uso_hash_abierto.o
	g++ -o $(BIN)/uso_hash_abierto $(OBJ)/uso_hash_abierto.o

